# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MergeInfo(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'schema_branch_name': 'str',
        'schema_version_id': 'int'
    }

    attribute_map = {
        'schema_branch_name': 'schemaBranchName',
        'schema_version_id': 'schemaVersionId'
    }

    def __init__(self, schema_branch_name=None, schema_version_id=None):
        """
        MergeInfo - a model defined in Swagger
        """

        self._schema_branch_name = None
        self._schema_version_id = None

        if schema_branch_name is not None:
          self.schema_branch_name = schema_branch_name
        if schema_version_id is not None:
          self.schema_version_id = schema_version_id

    @property
    def schema_branch_name(self):
        """
        Gets the schema_branch_name of this MergeInfo.

        :return: The schema_branch_name of this MergeInfo.
        :rtype: str
        """
        return self._schema_branch_name

    @schema_branch_name.setter
    def schema_branch_name(self, schema_branch_name):
        """
        Sets the schema_branch_name of this MergeInfo.

        :param schema_branch_name: The schema_branch_name of this MergeInfo.
        :type: str
        """

        self._schema_branch_name = schema_branch_name

    @property
    def schema_version_id(self):
        """
        Gets the schema_version_id of this MergeInfo.

        :return: The schema_version_id of this MergeInfo.
        :rtype: int
        """
        return self._schema_version_id

    @schema_version_id.setter
    def schema_version_id(self, schema_version_id):
        """
        Sets the schema_version_id of this MergeInfo.

        :param schema_version_id: The schema_version_id of this MergeInfo.
        :type: int
        """

        self._schema_version_id = schema_version_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MergeInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
