# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SchemaBranch(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'schema_metadata_name': 'str',
        'description': 'str',
        'timestamp': 'int'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'schema_metadata_name': 'schemaMetadataName',
        'description': 'description',
        'timestamp': 'timestamp'
    }

    def __init__(self, id=None, name=None, schema_metadata_name=None, description=None, timestamp=None):
        """
        SchemaBranch - a model defined in Swagger
        """

        self._id = None
        self._name = None
        self._schema_metadata_name = None
        self._description = None
        self._timestamp = None

        if id is not None:
          self.id = id
        if name is not None:
          self.name = name
        if schema_metadata_name is not None:
          self.schema_metadata_name = schema_metadata_name
        if description is not None:
          self.description = description
        if timestamp is not None:
          self.timestamp = timestamp

    @property
    def id(self):
        """
        Gets the id of this SchemaBranch.

        :return: The id of this SchemaBranch.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this SchemaBranch.

        :param id: The id of this SchemaBranch.
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """
        Gets the name of this SchemaBranch.

        :return: The name of this SchemaBranch.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this SchemaBranch.

        :param name: The name of this SchemaBranch.
        :type: str
        """

        self._name = name

    @property
    def schema_metadata_name(self):
        """
        Gets the schema_metadata_name of this SchemaBranch.

        :return: The schema_metadata_name of this SchemaBranch.
        :rtype: str
        """
        return self._schema_metadata_name

    @schema_metadata_name.setter
    def schema_metadata_name(self, schema_metadata_name):
        """
        Sets the schema_metadata_name of this SchemaBranch.

        :param schema_metadata_name: The schema_metadata_name of this SchemaBranch.
        :type: str
        """

        self._schema_metadata_name = schema_metadata_name

    @property
    def description(self):
        """
        Gets the description of this SchemaBranch.

        :return: The description of this SchemaBranch.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this SchemaBranch.

        :param description: The description of this SchemaBranch.
        :type: str
        """

        self._description = description

    @property
    def timestamp(self):
        """
        Gets the timestamp of this SchemaBranch.

        :return: The timestamp of this SchemaBranch.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """
        Sets the timestamp of this SchemaBranch.

        :param timestamp: The timestamp of this SchemaBranch.
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SchemaBranch):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
