# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SchemaIdVersion(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'schema_metadata_id': 'int',
        'version': 'int',
        'schema_version_id': 'int'
    }

    attribute_map = {
        'schema_metadata_id': 'schemaMetadataId',
        'version': 'version',
        'schema_version_id': 'schemaVersionId'
    }

    def __init__(self, schema_metadata_id=None, version=None, schema_version_id=None):
        """
        SchemaIdVersion - a model defined in Swagger
        """

        self._schema_metadata_id = None
        self._version = None
        self._schema_version_id = None

        if schema_metadata_id is not None:
          self.schema_metadata_id = schema_metadata_id
        if version is not None:
          self.version = version
        if schema_version_id is not None:
          self.schema_version_id = schema_version_id

    @property
    def schema_metadata_id(self):
        """
        Gets the schema_metadata_id of this SchemaIdVersion.

        :return: The schema_metadata_id of this SchemaIdVersion.
        :rtype: int
        """
        return self._schema_metadata_id

    @schema_metadata_id.setter
    def schema_metadata_id(self, schema_metadata_id):
        """
        Sets the schema_metadata_id of this SchemaIdVersion.

        :param schema_metadata_id: The schema_metadata_id of this SchemaIdVersion.
        :type: int
        """

        self._schema_metadata_id = schema_metadata_id

    @property
    def version(self):
        """
        Gets the version of this SchemaIdVersion.

        :return: The version of this SchemaIdVersion.
        :rtype: int
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this SchemaIdVersion.

        :param version: The version of this SchemaIdVersion.
        :type: int
        """

        self._version = version

    @property
    def schema_version_id(self):
        """
        Gets the schema_version_id of this SchemaIdVersion.

        :return: The schema_version_id of this SchemaIdVersion.
        :rtype: int
        """
        return self._schema_version_id

    @schema_version_id.setter
    def schema_version_id(self, schema_version_id):
        """
        Sets the schema_version_id of this SchemaIdVersion.

        :param schema_version_id: The schema_version_id of this SchemaIdVersion.
        :type: int
        """

        self._schema_version_id = schema_version_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SchemaIdVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
