# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SchemaRegistryVersion(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'version': 'str',
        'revision': 'str',
        'timestamp': 'int'
    }

    attribute_map = {
        'version': 'version',
        'revision': 'revision',
        'timestamp': 'timestamp'
    }

    def __init__(self, version=None, revision=None, timestamp=None):
        """
        SchemaRegistryVersion - a model defined in Swagger
        """

        self._version = None
        self._revision = None
        self._timestamp = None

        if version is not None:
          self.version = version
        if revision is not None:
          self.revision = revision
        if timestamp is not None:
          self.timestamp = timestamp

    @property
    def version(self):
        """
        Gets the version of this SchemaRegistryVersion.

        :return: The version of this SchemaRegistryVersion.
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """
        Sets the version of this SchemaRegistryVersion.

        :param version: The version of this SchemaRegistryVersion.
        :type: str
        """

        self._version = version

    @property
    def revision(self):
        """
        Gets the revision of this SchemaRegistryVersion.

        :return: The revision of this SchemaRegistryVersion.
        :rtype: str
        """
        return self._revision

    @revision.setter
    def revision(self, revision):
        """
        Sets the revision of this SchemaRegistryVersion.

        :param revision: The revision of this SchemaRegistryVersion.
        :type: str
        """

        self._revision = revision

    @property
    def timestamp(self):
        """
        Gets the timestamp of this SchemaRegistryVersion.

        :return: The timestamp of this SchemaRegistryVersion.
        :rtype: int
        """
        return self._timestamp

    @timestamp.setter
    def timestamp(self, timestamp):
        """
        Sets the timestamp of this SchemaRegistryVersion.

        :param timestamp: The timestamp of this SchemaRegistryVersion.
        :type: int
        """

        self._timestamp = timestamp

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SchemaRegistryVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
