# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class SerDesPair(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'description': 'str',
        'file_id': 'str',
        'serializer_class_name': 'str',
        'deserializer_class_name': 'str'
    }

    attribute_map = {
        'name': 'name',
        'description': 'description',
        'file_id': 'fileId',
        'serializer_class_name': 'serializerClassName',
        'deserializer_class_name': 'deserializerClassName'
    }

    def __init__(self, name=None, description=None, file_id=None, serializer_class_name=None, deserializer_class_name=None):
        """
        SerDesPair - a model defined in Swagger
        """

        self._name = None
        self._description = None
        self._file_id = None
        self._serializer_class_name = None
        self._deserializer_class_name = None

        if name is not None:
          self.name = name
        if description is not None:
          self.description = description
        if file_id is not None:
          self.file_id = file_id
        if serializer_class_name is not None:
          self.serializer_class_name = serializer_class_name
        if deserializer_class_name is not None:
          self.deserializer_class_name = deserializer_class_name

    @property
    def name(self):
        """
        Gets the name of this SerDesPair.

        :return: The name of this SerDesPair.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this SerDesPair.

        :param name: The name of this SerDesPair.
        :type: str
        """

        self._name = name

    @property
    def description(self):
        """
        Gets the description of this SerDesPair.

        :return: The description of this SerDesPair.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """
        Sets the description of this SerDesPair.

        :param description: The description of this SerDesPair.
        :type: str
        """

        self._description = description

    @property
    def file_id(self):
        """
        Gets the file_id of this SerDesPair.

        :return: The file_id of this SerDesPair.
        :rtype: str
        """
        return self._file_id

    @file_id.setter
    def file_id(self, file_id):
        """
        Sets the file_id of this SerDesPair.

        :param file_id: The file_id of this SerDesPair.
        :type: str
        """

        self._file_id = file_id

    @property
    def serializer_class_name(self):
        """
        Gets the serializer_class_name of this SerDesPair.

        :return: The serializer_class_name of this SerDesPair.
        :rtype: str
        """
        return self._serializer_class_name

    @serializer_class_name.setter
    def serializer_class_name(self, serializer_class_name):
        """
        Sets the serializer_class_name of this SerDesPair.

        :param serializer_class_name: The serializer_class_name of this SerDesPair.
        :type: str
        """

        self._serializer_class_name = serializer_class_name

    @property
    def deserializer_class_name(self):
        """
        Gets the deserializer_class_name of this SerDesPair.

        :return: The deserializer_class_name of this SerDesPair.
        :rtype: str
        """
        return self._deserializer_class_name

    @deserializer_class_name.setter
    def deserializer_class_name(self, deserializer_class_name):
        """
        Sets the deserializer_class_name of this SerDesPair.

        :param deserializer_class_name: The deserializer_class_name of this SerDesPair.
        :type: str
        """

        self._deserializer_class_name = deserializer_class_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, SerDesPair):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
