# coding: utf-8

"""
    Cloudera Edge Flow Manager REST API

    This REST API provides remote access to the EFM Server.                                             Endpoints that are marked as [BETA] are subject to change in future releases of the application without backwards compatibility and without a major version change.

    OpenAPI spec version: 1.0.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class AgentRepositories(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'flowfile': 'AgentRepositoryStatus',
        'provenance': 'AgentRepositoryStatus'
    }

    attribute_map = {
        'flowfile': 'flowfile',
        'provenance': 'provenance'
    }

    def __init__(self, flowfile=None, provenance=None):
        """
        AgentRepositories - a model defined in Swagger
        """

        self._flowfile = None
        self._provenance = None

        if flowfile is not None:
          self.flowfile = flowfile
        if provenance is not None:
          self.provenance = provenance

    @property
    def flowfile(self):
        """
        Gets the flowfile of this AgentRepositories.

        :return: The flowfile of this AgentRepositories.
        :rtype: AgentRepositoryStatus
        """
        return self._flowfile

    @flowfile.setter
    def flowfile(self, flowfile):
        """
        Sets the flowfile of this AgentRepositories.

        :param flowfile: The flowfile of this AgentRepositories.
        :type: AgentRepositoryStatus
        """

        self._flowfile = flowfile

    @property
    def provenance(self):
        """
        Gets the provenance of this AgentRepositories.

        :return: The provenance of this AgentRepositories.
        :rtype: AgentRepositoryStatus
        """
        return self._provenance

    @provenance.setter
    def provenance(self, provenance):
        """
        Sets the provenance of this AgentRepositories.

        :param provenance: The provenance of this AgentRepositories.
        :type: AgentRepositoryStatus
        """

        self._provenance = provenance

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, AgentRepositories):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
