# coding: utf-8

"""
    Cloudera Edge Flow Manager REST API

    This REST API provides remote access to the EFM Server.                                             Endpoints that are marked as [BETA] are subject to change in future releases of the application without backwards compatibility and without a major version change.

    OpenAPI spec version: 1.0.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class C2HeartbeatResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'requested_operations': 'list[C2Operation]'
    }

    attribute_map = {
        'requested_operations': 'requestedOperations'
    }

    def __init__(self, requested_operations=None):
        """
        C2HeartbeatResponse - a model defined in Swagger
        """

        self._requested_operations = None

        if requested_operations is not None:
          self.requested_operations = requested_operations

    @property
    def requested_operations(self):
        """
        Gets the requested_operations of this C2HeartbeatResponse.

        :return: The requested_operations of this C2HeartbeatResponse.
        :rtype: list[C2Operation]
        """
        return self._requested_operations

    @requested_operations.setter
    def requested_operations(self, requested_operations):
        """
        Sets the requested_operations of this C2HeartbeatResponse.

        :param requested_operations: The requested_operations of this C2HeartbeatResponse.
        :type: list[C2Operation]
        """

        self._requested_operations = requested_operations

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, C2HeartbeatResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
