# coding: utf-8

"""
    Cloudera Edge Flow Manager REST API

    This REST API provides remote access to the EFM Server.                                             Endpoints that are marked as [BETA] are subject to change in future releases of the application without backwards compatibility and without a major version change.

    OpenAPI spec version: 1.0.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FDPropertyDescriptor(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'property_descriptor': 'PropertyDescriptor'
    }

    attribute_map = {
        'property_descriptor': 'propertyDescriptor'
    }

    def __init__(self, property_descriptor=None):
        """
        FDPropertyDescriptor - a model defined in Swagger
        """

        self._property_descriptor = None

        if property_descriptor is not None:
          self.property_descriptor = property_descriptor

    @property
    def property_descriptor(self):
        """
        Gets the property_descriptor of this FDPropertyDescriptor.
        The property descriptor

        :return: The property_descriptor of this FDPropertyDescriptor.
        :rtype: PropertyDescriptor
        """
        return self._property_descriptor

    @property_descriptor.setter
    def property_descriptor(self, property_descriptor):
        """
        Sets the property_descriptor of this FDPropertyDescriptor.
        The property descriptor

        :param property_descriptor: The property_descriptor of this FDPropertyDescriptor.
        :type: PropertyDescriptor
        """

        self._property_descriptor = property_descriptor

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FDPropertyDescriptor):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
