# coding: utf-8

"""
    Cloudera Edge Flow Manager REST API

    This REST API provides remote access to the EFM Server.                                             Endpoints that are marked as [BETA] are subject to change in future releases of the application without backwards compatibility and without a major version change.

    OpenAPI spec version: 1.0.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Link(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'href': 'str',
        'rel': 'str',
        'title': 'str',
        'type': 'str',
        'params': 'dict(str, str)'
    }

    attribute_map = {
        'href': 'href',
        'rel': 'rel',
        'title': 'title',
        'type': 'type',
        'params': 'params'
    }

    def __init__(self, href=None, rel=None, title=None, type=None, params=None):
        """
        Link - a model defined in Swagger
        """

        self._href = None
        self._rel = None
        self._title = None
        self._type = None
        self._params = None

        if href is not None:
          self.href = href
        if rel is not None:
          self.rel = rel
        if title is not None:
          self.title = title
        if type is not None:
          self.type = type
        if params is not None:
          self.params = params

    @property
    def href(self):
        """
        Gets the href of this Link.

        :return: The href of this Link.
        :rtype: str
        """
        return self._href

    @href.setter
    def href(self, href):
        """
        Sets the href of this Link.

        :param href: The href of this Link.
        :type: str
        """

        self._href = href

    @property
    def rel(self):
        """
        Gets the rel of this Link.

        :return: The rel of this Link.
        :rtype: str
        """
        return self._rel

    @rel.setter
    def rel(self, rel):
        """
        Sets the rel of this Link.

        :param rel: The rel of this Link.
        :type: str
        """

        self._rel = rel

    @property
    def title(self):
        """
        Gets the title of this Link.

        :return: The title of this Link.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """
        Sets the title of this Link.

        :param title: The title of this Link.
        :type: str
        """

        self._title = title

    @property
    def type(self):
        """
        Gets the type of this Link.

        :return: The type of this Link.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this Link.

        :param type: The type of this Link.
        :type: str
        """

        self._type = type

    @property
    def params(self):
        """
        Gets the params of this Link.

        :return: The params of this Link.
        :rtype: dict(str, str)
        """
        return self._params

    @params.setter
    def params(self, params):
        """
        Sets the params of this Link.

        :param params: The params of this Link.
        :type: dict(str, str)
        """

        self._params = params

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Link):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
