# coding: utf-8

"""
    Cloudera Edge Flow Manager REST API

    This REST API provides remote access to the EFM Server.                                             Endpoints that are marked as [BETA] are subject to change in future releases of the application without backwards compatibility and without a major version change.

    OpenAPI spec version: 1.0.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ListContainer(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'elements': 'list[object]',
        'links': 'PageLinks',
        'page': 'PageMetadata'
    }

    attribute_map = {
        'elements': 'elements',
        'links': 'links',
        'page': 'page'
    }

    def __init__(self, elements=None, links=None, page=None):
        """
        ListContainer - a model defined in Swagger
        """

        self._elements = None
        self._links = None
        self._page = None

        if elements is not None:
          self.elements = elements
        if links is not None:
          self.links = links
        if page is not None:
          self.page = page

    @property
    def elements(self):
        """
        Gets the elements of this ListContainer.
        The elements of the list

        :return: The elements of this ListContainer.
        :rtype: list[object]
        """
        return self._elements

    @elements.setter
    def elements(self, elements):
        """
        Sets the elements of this ListContainer.
        The elements of the list

        :param elements: The elements of this ListContainer.
        :type: list[object]
        """

        self._elements = elements

    @property
    def links(self):
        """
        Gets the links of this ListContainer.
        Hypermedia links to other pages, when in a pageable context

        :return: The links of this ListContainer.
        :rtype: PageLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """
        Sets the links of this ListContainer.
        Hypermedia links to other pages, when in a pageable context

        :param links: The links of this ListContainer.
        :type: PageLinks
        """

        self._links = links

    @property
    def page(self):
        """
        Gets the page of this ListContainer.
        The metadata of the current page, when in a pageable context

        :return: The page of this ListContainer.
        :rtype: PageMetadata
        """
        return self._page

    @page.setter
    def page(self, page):
        """
        Sets the page of this ListContainer.
        The metadata of the current page, when in a pageable context

        :param page: The page of this ListContainer.
        :type: PageMetadata
        """

        self._page = page

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ListContainer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
