# coding: utf-8

"""
    Cloudera Edge Flow Manager REST API

    This REST API provides remote access to the EFM Server.                                             Endpoints that are marked as [BETA] are subject to change in future releases of the application without backwards compatibility and without a major version change.

    OpenAPI spec version: 1.0.0-SNAPSHOT
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ResourceReference(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'type': 'str',
        'id': 'str',
        'parent': 'ResourceReference'
    }

    attribute_map = {
        'type': 'type',
        'id': 'id',
        'parent': 'parent'
    }

    def __init__(self, type=None, id=None, parent=None):
        """
        ResourceReference - a model defined in Swagger
        """

        self._type = None
        self._id = None
        self._parent = None

        if type is not None:
          self.type = type
        if id is not None:
          self.id = id
        if parent is not None:
          self.parent = parent

    @property
    def type(self):
        """
        Gets the type of this ResourceReference.

        :return: The type of this ResourceReference.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """
        Sets the type of this ResourceReference.

        :param type: The type of this ResourceReference.
        :type: str
        """
        if type is not None and len(type) > 200:
            raise ValueError("Invalid value for `type`, length must be less than or equal to `200`")
        if type is not None and len(type) < 0:
            raise ValueError("Invalid value for `type`, length must be greater than or equal to `0`")

        self._type = type

    @property
    def id(self):
        """
        Gets the id of this ResourceReference.

        :return: The id of this ResourceReference.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this ResourceReference.

        :param id: The id of this ResourceReference.
        :type: str
        """
        if id is not None and len(id) > 4096:
            raise ValueError("Invalid value for `id`, length must be less than or equal to `4096`")
        if id is not None and len(id) < 0:
            raise ValueError("Invalid value for `id`, length must be greater than or equal to `0`")

        self._id = id

    @property
    def parent(self):
        """
        Gets the parent of this ResourceReference.

        :return: The parent of this ResourceReference.
        :rtype: ResourceReference
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """
        Sets the parent of this ResourceReference.

        :param parent: The parent of this ResourceReference.
        :type: ResourceReference
        """

        self._parent = parent

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ResourceReference):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
